name: 'olxbr/use-private-action'
description: 'This action allows you to use private actions.'
author: 'olxbr'
inputs:
  private-action:
    description: 'Private action to execute, format: {repo}'
    required: true
  private-action-token:
    description: 'Token to access the private repository'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout olxbr/${{ inputs.private-action }}
      uses: actions/checkout@v2
      with:
        repository: olxbr/${{ inputs.private-action }}
        ref: refs/heads/main
        token: ${{ inputs.private-action-token }}
        persist-credentials: false
        path: ./.github/actions/${{ inputs.private-action }}

    - name: Execute action ${{ inputs.private-action }}
      id: ${{ inputs.private-action }}
      uses: ./.github/actions/${{ inputs.private-action }}
      with:
        who-to-greet: 'Olx Brasil'
