name: 'olxbr/use-private-action'
description: 'This action allows you to use private actions.'
author: 'olxbr'
inputs:
  private-action:
    description: 'Private action to execute, format: {repo}'
    required: true
  private-action-token:
    description: 'Token to access the private repository'
    required: true
  private-action-ref:
    description: 'Version, branch, hash or tag'
    required: true
outputs:
  action-path:
    description: 'Action path to use in next steps'
runs:
  using: 'composite'
  steps:
    - run: | 
        mkdir -p ./.github/actions
        cd ./.github/actions
        git clone https://${{ inputs.private-action-token }}:x-oauth-basic@github.com/olxbr/${{ inputs.private-action }}.git
        git checkout ${{ inputs.private-action-ref }}
      shell: bash